[package]
name = "bin_exe_machine_learning"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bin_exe_machine_learning"
path = "main.rs"

[dependencies]
my_stats_package = { path = "../../my_stats_package" }
